version: '3.2'

services:

  frontend:
    build: frontend
    container_name: frontend
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  backend:
    build: backend
    container_name: backend
    ports:
      - 21081:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  #db:
  #  image: mysql:latest
  #  container_name: db
  #  restart: unless-stopped
  #  networks: 
  #    - default
  #  ports:
  #    - "3336:3306"
  #  environment:
  #    - MYSQL_ROOT_PASSWORD=12345
  #    - MYSQL_DATABASE=base
  #  volumes:
  #    - "./database:/var/lib/mysql"

  pgsql:
    image: postgres:11.9
    container_name: pgsql
    restart: unless-stopped
    networks: 
      - default
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=base
      - POSTGRES_USER=yii2_user
      - POSTGRES_PASSWORD=12345
    volumes:
      - ./postgresData:/var/lib/postgresql/data
  
  pgsql-admin:
    image: dpage/pgadmin4
    container_name: pgsql-admin
    restart: always
    depends_on:
      - pgsql
    ports:
      - "22080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    links:
      - "pgsql:pgsql-server"